name: 'kubernetes'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
target-path: "target"
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kubernetes:
    staging:
      +schema: main
